name: "Destroy Infrastructure"

on:
  workflow_dispatch:
  schedule:
    - cron: '1/2 * * * *' # Run every 2 hours

permissions:
  id-token: write
  contents: read
jobs:
  terraform-destroy-infra:
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: infra/
      destroy: true
      environment: development
      aws-region: eu-west-2
    secrets:
      AWS_ACCESS_KEY_PLATFORM: ${{ secrets.AWS_ACCESS_KEY_PLATFORM }}
      AWS_ACCESS_SECRET_KEY_PLATFORM: ${{ secrets.AWS_ACCESS_SECRET_KEY_PLATFORM }}
      TF_VAR_DB_PASSWORD: ${{ secrets.TF_VAR_DB_PASSWORD }}
      TF_VAR_GITHUB_PAT: ${{ secrets.TF_VAR_GITHUB_PAT }}


  terraform-destroy-backup:
      uses: ./.github/workflows/_terraform.yml
      needs: terraform-destroy-infra
      with:
        working-directory: backup/
        destroy: true
        environment: backup
        aws-region: eu-west-1
      secrets:
        AWS_ACCESS_KEY_PLATFORM: ${{ secrets.AWS_ACCESS_KEY_PLATFORM }}
        AWS_ACCESS_SECRET_KEY_PLATFORM: ${{ secrets.AWS_ACCESS_SECRET_KEY_PLATFORM }}



  terraform-destroy-restore-testing:
      uses: ./.github/workflows/_terraform.yml
      needs: terraform-destroy-backup
      with:
        working-directory: restore_testing/
        destroy: true
        environment: restore-testing
        aws-region: eu-west-1
      secrets:
        AWS_ACCESS_KEY_PLATFORM: ${{ secrets.AWS_ACCESS_KEY_PLATFORM }}
        AWS_ACCESS_SECRET_KEY_PLATFORM: ${{ secrets.AWS_ACCESS_SECRET_KEY_PLATFORM }}
