name: "Pull Request"

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan-development:
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: infra/
      Deploy: false
      environment: development
      aws-region: eu-west-2
    secrets:
      AWS_TERRAFORM_ROLE_ARN: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
      TF_VAR_DB_PASSWORD: ${{ secrets.TF_VAR_DB_PASSWORD }}
      TF_VAR_GITHUB_PAT: ${{ secrets.TF_VAR_GITHUB_PAT }}

  terraform-plan-production:
    uses: ./.github/workflows/_terraform.yml
    needs: terraform-plan-development
    with:
      working-directory: infra/
      Deploy: false
      environment: production
    secrets:
      AWS_TERRAFORM_ROLE_ARN: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
      TF_VAR_DB_PASSWORD: ${{ secrets.TF_VAR_DB_PASSWORD }}
      TF_VAR_GITHUB_PAT: ${{ secrets.TF_VAR_GITHUB_PAT }}