name: "Deploy Restore Testinf"

on:
 workflow_dispatch:
    inputs:
      Deploy:
        description: "Whether to deploy the Terraform plan"
        required: true
        type: boolean
        default: true
      aws-region:
        description: "AWS region to run the restore testing against (e.g. to test restore from DR region)"
        type: string
        default: eu-west-1
      environment:
        description: "GitHub environment to run the job under (optional)"
        type: string
        default: restore_testing
   

permissions:
  id-token: write
  contents: read
jobs:
  terraform-deploy:
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: restore_testing/
      Deploy: true
      aws-region: eu-west-1
      environment: restore_testing
    secrets:
      AWS_ACCESS_KEY_PLATFORM: ${{ secrets.AWS_ACCESS_KEY_PLATFORM }}
      AWS_ACCESS_SECRET_KEY_PLATFORM: ${{ secrets.AWS_ACCESS_SECRET_KEY_PLATFORM }}